apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api-crud-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-crud-golang
  template:
    metadata:
      labels:
        app: api-crud-golang
    spec:
      containers:
      - name: api-crud-golang
        image: nathansnts/api-crud
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-crud-golang
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer